cms2l2v/2l2v_fwk

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, src/PatUtils.cc
This PR was also made in https://github.com/quertenmont/2l2v_fwk/pull/53 
Update of the PUJetID lookinga at miniAOD V1
1) Suppression of the cuts at high pseudo-rapidity in PatUtils.cc
Update of the PUJetID looking at miniAOD V2
2) Since miniAOD V2 are bugged for the PUJetID, suppression of this cleaning in the hzz2l2nu code
=> Update of the PUJetID for miniAOD V2

bin/chhiggs/runAnalysis.cc, interface/PatUtils.h, src/PatUtils.cc
I realized that it was implicitly converting to GsfElectron.
Sorry for the double pull in a so short amount of time.
=> Updated electron ID to pat::Electron class

test/hzz2l2v/samples.json
Hi all,
I added the following samples:
1- /VBF_HToZZTo2L2Nu_M1000_13TeV_powheg_JHUgen_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
2- /GluGluHToZZTo2L2Nu_M1000_13TeV_powheg_JHUgen_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
3- /WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
and the Inclusive ZZ is replaced by:
4- /ZZTo2L2Nu_13TeV_powheg_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM
Cheers,
Alessio
=> New Samples using New MiniAOD

test/hzz2l2v/photon_samples.json
Hi Xin,
Done .  Indeed the DY xsec I had put there for the 10<M<50 sample was the NNLO one , but for consistency with the DY M>50 sample we switch to the NLO values for both samples.
cheers, Georgia
=> dropped split keyword + DY xsec switched from NNLO to NLO

test/hzz2l2v/samples.json
Hi all,
I have added the TTZ sample to the json file. Now all the samples are also updated to AN except the ones used by Georgia (at the moment, i will fix it as soon as possible).
All the cross sections come from this official twiki: https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns
Alessio
=> Added TTZ samples

test/hzz2l2v/samples.json
Hi all,
the current version of the signal sample for VBF with Mass = 1000 GeV, present in the sample.json was tagged as INVALID. 
The proper version now is v2.
Alessio
=> Change version of VBF_H_ToZZ_M1000GeV Version

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, test/hzz2l2v/samples_ctrl.json
Hi @amagitte ,
I saw that one needs to put the variable "isPromptReco" to true for Run2015D PromptReco datasets as well (otherwise the code crashes , e.g. on SinglePhoton Run2015D PromptReco because of ProductNoFound in TriggerResults ) .
Currently this variable is only set to true for RunB PromptReco . Do you agree to change this as in my fix here?
Thanks, Georgia
=> fix when using METfilters with Run2015D

bin/chhiggs/runAnalysis.cc, interface/PatUtils.h, src/PatUtils.cc
Dear All,
src/PatUtils.cc contains the method to be used, and also the commented snipped you are supposed to put in the analysis executable.
The list of the samples supported is there as well. 
I tested it on my tau fakes software.
Best regards,
Pietro
=> Added stitching procedure for HT-binned W+Jets and Drell-Yan samples

src/PatUtils.cc
Hi guys,
sorry, I had forgotten to commit the line for rescaling the scale factors in order to use them when rescaling to a luminosity expressed in inverse picobarn (they are for luminosity expressed in inverse femtobarn). 
Tested, it works (it is actually what I had tested a couple days ago, but that last line was not in the latest commit)
Best,
Pietro
=> Patch scale factor units for stitching

scripts/runAnalysisOverSamples.py
Due to an update of the procedure to get new certificates at IIHE, the submission procedure doesn't need anymore the becms argument.
Therefore I decided to partially port back the submission procedure, simplifying it by removing some specific iihe lines.
For iihe people:
-------------------------
If you are using a CERN certificate (and it is what is advised from now on --> only one certificate for everything), then it will work.
If you still use a old belnet certificate, you have two options:
- adding by hand the --voms cms:/cms/becms in scripts/runAnalysisOverSamples.py when you run on m machines (see my commit)
- follow this twiki (http://doc.iihe.ac.be/wiki/t2b/index.php/Getting_a_certificate_for_the_T2) to add your CERN certificate on the m machines instead of the belnet one.
If you …
=> [For iihe people, please read] Simplification of the submission procedure for iihe

test/hzz2l2v/missing_samplesFor2016.json, test/hzz2l2v/samples2015.json, test/hzz2l2v/samples2016.json
Dear all,
Here are the new json files for 2016 data and MC (80X).
They are 3 json:
- samples2015.json                           which contains the data and MC for 2015 in 76X
- sampes2016.json                            which contains the data and MC for 2016 in 80X
- missing_samplesFor2016.json       which contains what is currently not in 80X for MC [see WARNING at the end]
The final goal is obviously to, one day, get rid of this missingFrom2016.json since nothing will be missing in 80X and everything will be in 2016.json
With those three json, the (idea of) workflow will be the following:
FOR 2016:
———————
- run samples2016.json with the code in 80X
- run missing_samplesFor2016.json with the code in 76X
- copy the root files from 80X in 76X, so we have all the files we need at a single …
=> Adding new json files for treating with 2016 MC and data

README.md
This gives the current instructions to be able to work with the code in 80X.
It can look a bit tricky, but the way it is done allows to keep a single code for both 76X and 80X.
Furthermore, I didn't wanted to add any of those changes permanently since it is meant to be fixed one day.
Tell me if you have any question or if you would like to see this done differently.
Cheers,
-Hugo
=> Update README.md for 80X

bin/common/computeLimit.cc
Now it's implemented in the code, and is dependant on m_wz.
=> Removed the 3% constant uncertainty for WZ EWK corrections

scripts/runAnalysisOverSamples.py
New DAS client adds two features:
- it asks for proxy on the local machine to perform the DAS request --> fixed by copying the proxy also in /tmp/
- it changed the output format when requesting site information --> fixed by changing the way we play with the string
In practice:
- no need anymore to do a voms-proxy-init by hand before launching the script
- won't complain anymore
=> Fix troubles coming from update of DAS CLI

bin/BuildFile.xml, bin/hzz2l2v/extractPhotonWeights_UsingBins.cc, bin/hzz2l2v/runPhotonZClosure.cc, test/hzz2l2v/samples2016.json
-- added new code for photonZ closure tests -> runPhotonZClosure (+ Buildfile updated )
-- fixed samples2016.json for proper labels to run photon+jet analysis
-- fixed extractPhotonWeights_UsingBins to pick up the correct photon distributions (non-reweighted ones)
-- updated DY sample to increase statistics to 100M 
-- updated DY cross-section from recommendations ( ~5% lower to what we had )
=> updates and fixes for photonZ analysis

test/hzz2l2v/samples2016.json
Adding the WJetsToLNu MC sample from the extension , provides another ~50M in addition to the ~10M we had .
=> updated wjets sample to increase stats.

test/hzz2l2v/samples2016.json
o added missing Z(->nunu)+g samples, and T+g, TT+g as well
o updated Z->nunu (in HTbinned) xsections
o now W+jets,HT>100 runs only in photon CR -- W+jets inclusive in SR
o instr. MET obtained by subtracting also the EWK samples: Z(->nunu)+g, Z->tautau, Top/WZ/WW, Top+g
o added missing QCD bin HT100to200 sample
=> additions and fixes for MC samples

src/GammaWeightsHandler.cc, test/hzz2l2v/samples2016.json, test/hzz2l2v/samples_ichep2016.json, test/hzz2l2v/submit.sh
- fixed bug with instr. MET in mumu 0-jet bin 
- added option to run the photon re-weighting with MC weights
- photon weights with 'bin-method' by default for the moment
- removed W->qq process, no need 
- new input samples_ichep2016.json to remove spin-2 models (RsGrav, BulkGrav)
=> residual fixes and updates

bin/common/runPlotter.cc
- increased upper limit  in number of sub-histograms to consider for each kind . The problem was that if the first sub-histograms were empty, the type of histogram would be skipped.
=> small fix in runPlotter

scripts/LaunchOnCondor.py
- update walltime for IIHE submission from 168h to 20h
- remove specification of the queue since localgrid is now the default queue
=> Update walltime for IIHE submission

src/EwkCorrections.cc
Update to switch from the NNPDF23 to the LUXqed photon PDF:
- Applied an actual correction due to both virtual and photon-induced contributions
- Removed the uncertainty from photon PDFs (as it was smaller than 0.1%)
=> Update EWK corrections on WZ with LUXqed photon PDF

scripts/LaunchOnCondor.py
This PR only affects IIHE submission.
It merges the stderr and stdout into a single file.
Furthermore, let me take this opportunity to introduce you a new feature of the cluster: qpeek.
*qpeek* allows you to look at the output of a job when it is still running.
How it works:
- connect with ssh -A  <+other options>     to *m0*
- qpeek           => it gives you the different options of the script
- qpeek -f JOBID   => does a tail -f (and keep listening) on the output file of your job (you can find your job ID with qstat -u $USER); if you want to see the full log (at a given moment of time), just do a "qpeek JOBID".
=> [IIHE-only] Better outputs + qpeek explanations

src/PatUtils.cc
Following the recommandation here : https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016 (27-dec-2016) I've updated the jetID.
For the 13 TeV analysis for promt and rereco data of Run2016 the same recommendations as before are valid for |eta|<2.7 and 3<|eta|<5.
For 2.7< |eta|<3 the JetID criteria have been changed (see commit) in order to increase the efficiency and background rejection as well. For more details look at the twiki.
For |eta|>2.7 Loose and Tight criteria are identical as before.
=> Update Jet PF ID

interface/MacroUtils.h, src/MacroUtils.cc, src/PatUtils.cc
Hi,
I have removed cone variable from getEffectiveArea function, which was useless. Also as Hugo suggested (and discussed with Hugues) trkrelIso has been removed.
=> removed cone from getEffectiveArea and trkIso from Muon

scripts/runAnalysisOverSamples.py
This commit affects IIHE only.
It changes the limitation of ROOT files per job:
- from 8 to 6 as default value
- remove the limitation of maximum number of jobs per dataset (was set to 100 before, which creates jobs with 20-30 ROOT files (!) hence copying 60GB to the scratch area...)
Please do NOT RUN at IIHE with the old options... you will be killed ;-)
=> [IIHE-ONLY] Comply with cluster rules

bin/common/computeLimit.cc
This will add the uncertainties due to scale variations for ZZ/WZ as hardcoded uncertainties in the data cards (see my last talk to see where these numbers come from).
(It has already been documented in the AN.)
=> Add mu_R/mu_F systematic uncertainties on WZ/ZZ backgrounds

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, src/PatUtils.cc
Dear All,
Based on yesterday's study I have changed the code for tkHighPt ID with tkIso.
Also I saw we have many signal samples with reHLT. These reHLT samples have HLT2[*] as process name.
So I keep protection against that. 
[*]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD#Run2_Spring16_reHLT_campaign_80X
=> tkHighPt ID with tkISo and protection against reHLT samoples

README.md
This fixes the layout of the markdown.
Is there a reason why we didn't update once for all the Buildfile.xml with MELA? Since it is needed to compile?
=> Quick fix of the readme

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, interface/PatUtils.h, src/PatUtils.cc
update of the muon consistently with [HZZ4l TWiki ](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsZZ4l2016)
The **loose ID** is replaced by **TightID** for muon with pT < 200 to not increase background too much
_before PR_
_after PR_
=> update muon ID consistently with Hzz4l

test/hzz2l2v/samples_full2016.json
I have removed ggZZ Bckg from the main json file to avoid the double counting with the BOnly sample
=> Remove ggZZ Bckg from the json file

bin/common/runPlotter.cc, test/hzz2l2v/samples_full2016.json, test/hzz2l2v/samples_full2016_GGH.json
Replaced DYJetsToLL M50toInf sample (~1M events ) with Madgraph extension samples (total ~150M events ) .
=> new madgraph DY M50toInf sample

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, interface/PatUtils.h, src/PatUtils.cc
Here the PR, 
Apologize for the non really clean PR, there are some debug lines that I will remove in the futur.
Also I duplicate the passIso for muon to be sure that the isolation behaviour will be identical in the other part of the code which are calling the passIso function. 
I checked on DY the new ID and I see almost identical distributions (see for example the z mass in attachment). A test on ggH3000 is running (but they are a lot of debug lines which make the test slow in interactive).
*before PR=*
*after PR=*
=> update for using the isolation safe on boosted Z

bin/common/computeLimit.cc
Two lines to remove BOnly and SandBandInterf from Mt distributions
=> Remove BOnly and SnadBandInterf from Mt shape

interface/MacroUtils.h
Hi 
I forget to add Slew rate function deceleration in MacroUtils.h file.
Not it is added, it must compiles now.
I have checked too.
=> debug for slewrate correction

test/hzz2l2v/samples_re-miniAOD_full2016_GGH.json
do *not* use yet with current analysis code =>
- waiting for PR from Sumit to remove slew rate corrections for electrons
- JECs v3 are applied for jets in data . One can re-apply JECs v4 that are currently implemented by Li
=> added separate json with re-miniAOD data

bin/common/computeLimit.cc
Hi All,
We have updated systematics for Electron and Muon in computeLimit code.
These numbers are based on sum in quadrature of all the errors on SF coming from either Trigger SFs or ID and Iso SFs.
These numbers are produced with the help of @HuguesBrun and @amagitte .
I got these numbers  from Alessio today. 
In case of any question then please don't hesitate!
=> updated Systematics for electron and Muon

interface/PatUtils.h, src/PatUtils.cc
Dear All,
Two variables one sigmaietaieta and other dEtaIn were not calculated in correct way in the code for electrons ID. This was pointed out by Alessio. So I have corrected those two variables following the link from twiki page[*].
[*] https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Working_points_for_2016_data_for
=> some minor changes in electron's passID function

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, test/hzz2l2v/submit.sh
I removed the OR with VBF photon paths , in the photon trigger list . I noticed that they introduce an increased data-MC discrepancy in the control region . 
Since they are not really playing a big role other than for the VBF channel , I suggest to remove them completely for this phase of the Analysis.
cheers, georgia
=> removed VBF paths in photon analysis

bin/hzz2l2v/runPhotonZClosure.cc, test/hzz2l2v/submit.sh
in photonZ closure tests:
- now channel ("ll", "ee" or "mumu" ) is passed as argument
- fixed bug when running ee or mumu channels separately
=> small update to separate channels

scripts/runAnalysisOverSamples.py
This hot fix removes the maximum number of jobs per dataset when submitting outside of iihe.
=> Hot fix for submission at lxplus

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, src/MacroUtils.cc
Hi,
I have added all the suggestions from Hugo. But for double sure please check it first.
Here I made following changes.
In file runHZZ2l2vAnalsis.cc -- 
line 1273 : added leptons[ilep] = patUtils::GenericLepton(leptons[ilep].el); 
In file MacroUtils.cc --
1) Keep Ecorr=1 and TLorentzVector (line 458 and 459) outside the if condition. This if condition checks if the electron is in Barrel. Since this correction has to be applied only on Barrel Electron. So if electron is not in Barrel then Ecorr=1 and Electron will not get any slew correction.
2) Applied Ecorr on all px,py,pz and E. (line 459)
Sumit
=> Fix slew rate, incorprating Hugo's suggestions

test/hzz2l2v/computeLimit/optimize.py, test/hzz2l2v/computeLimit/optimize_WideWidth.py
This is a bit counter intuitive, I may think of a prettier fix when have time.
Since in the shapes we added one bin, we have to use the bin projection 17 instead of 16. However the optimize.py code performs some checks with the associated value and one has to increase the associated value accordingly (going from 125 to 130).
So this cut is really the one corresponding to 125 even if it can look different at first sight. I will improve this to make it more intuitive when having more time but the machinery was not meant to have a cut with 0 and then starting with cuts at 50, 55, 60 etc.
=> Small fix for optimize projection bin

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, test/hzz2l2v/samples_full2016_GGH.json, test/hzz2l2v/samples_re-miniAOD_full2016_GGH.json
- The t-channel samples for top and antitop had to be updated . In fact it seems we were completely ignoring the t-channel_top previously - we need to check now for any improvement in the data-MC agreement in the signal region . NRB needs to be redone as well .
- I also remove overlaps now between processes : W->lnu and Wg->lnug as well as Z->nunu and  Zg -> nunug in the same way as was done between plain QCD and G+jets. This is to improve the data-MC agreement in the photon control sample due to the genuine Met EWK processes.
=> updates for single top samples + overlaps in X and X+g

bin/hzz2l2v/runHZZ2l2vAnalysis.cc, test/hzz2l2v/samples_full2016_GGH.json
This applies a differential NLO/LO correction for the ZnunuG sample instead of the previous "times 2" that was applied.
It is done as a function of the pt of the Z->nunu at gen lvl.
Also, while doing this I noticed a (probable?) typo for recHitCollectionEEHandle. I fixed it, but please cross-check. I think it can give pretty interesting changes.
=> ZnunuG differential NLO/LO k-factor + fix?

interface/LeptonEfficiencySF.h
Hi All,
I have updated new Trigger SFs. These SFs are computed by ORing HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v* OR HLT_DoubleEle33_CaloIdL_v* OR SingleEle27_WPTight.
The purpose of taking OR with DoubleEle33 is to recover efficiency beyond 400 GeV. I have attached few slides with detailed study. 
I have used Tag and probe method to compute these SFs. All the SF's values are nearly equal to 1 as expected. 
Please let me know in case of any doubt and further questions or cross checks.
Thanks.
[HightPtTriggerIssueNewSF.pdf](https://github.com/cms2l2v/2l2v_fwk/files/1033932/HightPtTriggerIssueNewSF.pdf)
=> Added new Trigger SF

bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Hi Georgia,
The SF's are computed by doing OR with **HLT_DoubleEle33_CaloIdL_v*** path. But When I'm looking in our main analysis code it is not there. So I'm creating another PR by adding this path.
Sumit.
=> Added HLT_DoubleEle33_CaloIdL_v* trigger

test/hzz2l2v/macro_Intr_MET_Syst/MakeSyst_custom_forMTandMET.C, test/hzz2l2v/macro_Intr_MET_Syst/produceInstrMET_syst_rootFiles_NOCORRECTIONS.sh
This PR adds the possibility to remove the corrections coming from uncertainties on the genuine MET processes. For this just use the new script: produceInstrMET_syst_rootFiles_NOCORRECTIONS.sh
It also adds the stat on the genuine MET processes together with the stat on the gamma+jets data.
Eventually, it corrects the uncertainty on the k-factor for the ZGamma process.
=> Latest update on InstrMET

bin/common/computeLimit.cc
the shapeN2 is causing problem because of the bins where the value is 0 in the MET template
=> use of the shape2 to for the inst. MET
