- test/hzz2l2v/samples.json
I forgot a comma in the json file..sorry.
Alessio
> Fix a comma

- bin/chhiggs/runAnalysis.cc
- bin/chhiggs/runNtuplizer.cc
- data/chhiggs/plot_chhiggs_dileptons.json
- data/chhiggs/plot_chhiggs_leptontau.json
- scripts/LaunchOnCondor.py
- test/chhiggs/countBatchJobs.sh
- test/chhiggs/doAnal.sh
- test/runAnalysis_cfg.py.templ
Minor change to LaunchOnCondor and runAnalysis_cfg.py.templ to revert to only one single output file when running on CRAB.
No impact on the rest of the people :)
> Minor changes

- test/hzz2l2v/photon_samples.json
> updated photon samples

- src/PatUtils.cc
Hi,
I have updated electron cut-based ID for spring15 selections.
Have a look.
> Updated Electron ID

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- test/hzz2l2v/samples.json
Hi Xin,
As you suggested, here you are the changes that I used to produce the plots that we discussed one hour ago.
Alessio
> New Label and New Sample

- test/hzz2l2v/phojet/macros/makePhoJetClosure.C
- test/hzz2l2v/phojet/macros/make_weights.C
Hi Loic,Xin
These are the macros I use to make the photon weights and the closure tests  . I will show their improved results next week .Thanks, Georgia
> added MET template macros

- test/hzz2l2v/photon_samples.json
Hi Xin and Georgia,
@georgia14: I have updated the MC using MiniAODv2. For the data: at the moment I added only runD, I am trying to understand (the same problem is present in the json file of the analysis) if we can already use runC.
When I receive some news, I will change the file.
Have a nice day!
Alessio
> MiniAOD v2 + Data RunD

- bin/common/computeLimit.cc
- bin/common/runPlotter.cc
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/MacroUtils.h
- src/HiggsUtils.cc
- test/hzz2l2v/samples.json
- test/hzz2l2v/submit.sh
> Jamboree approved

- bin/chhiggs/runAnalysis.cc
- bin/common/runEfficencyMiniAODExample.cc
- bin/common/runPlotter.cc
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/MacroUtils.h
- interface/PatUtils.h
- scripts/runAnalysisOverSamples.py
- src/MacroUtils.cc
- src/PatUtils.cc
- test/hzz2l2v/submit.sh
@vischia note that I also added the default metFilter for chhiggs analysis,
So please verify that I did not introduce bugs there.
> cleanup met filter and other small bugs

- scripts/LaunchOnCondor.py
Small fix to the submission at iihe
> Fix submission at iihe

- bin/common/runPlotter.cc
- bin/zhtautau/runZHTauTauAnalysis.cc
- scripts/runAnalysisOverSamples.py
- Fix to ZHtautau code (dilId and tau ID)
- Fix to runAnalysis to consider local samples when sample fraction never reach 100%
- Temporarilly add warning in runPlotter to debug some plots
> fix in zhtautau and add cases for not complete samples

- bin/common/runPlotter.cc
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- bin/zhtautau/runZHTauTauAnalysis.cc
- scripts/runAnalysisOverSamples.py
- src/MacroUtils.cc
- test/hzz2l2v/submit.sh
- test/runAnalysis_cfg.py.templ
- test/zhtautau/samples.json
- test/zhtautau/submit.sh
@vischia Please also update your PU reweighting function to the official Interaction based instead of Vtx based pileup reweighting.  Otherwise the pileup vector  test/runAnalysis_cfg.py.templ will lead to disastrous results.
> cleanup, add PU reweighting

- bin/common/computeLimit.cc
Hi,
I have fixed the bug in the error of the alpha value for mumu channel.
Alessio
> Fix error in alpha mumu

- bin/common/runPlotter.cc
> fix plotter axis legends

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- bin/zhtautau/runZHTauTauAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
data/MC normalization improves from ~20% to ~5% disagreement.
The remaining difference is certainly due to the missing scale factors (trigger efficiency correction and lepton scale corrections).
> fix but in MEt filters inducing data/MC disagreement

- test/hzz2l2v/phojet/macros/make_weights.C
Hi Loic,
I think these small fixes will solve all the errors you saw . Let me know in case
Cheers, Georgia
> fixed eff function errors

- bin/zhtautau/runZHTauTauAnalysis.cc
- test/zhtautau/samples.json
- test/zhtautau/submit.sh
Fixes several issues + adds ZZto4L and ZH->tautatu samples in the mc samples json
> Fixes zhtautau analysis

- bin/zhtautau/runZHTauTauAnalysis.cc
- test/zhtautau/samples.json
Regrouped MC background samples in the JSON file and added signal samples as well
> Adding fully leptonic final states in the analysis 

- bin/common/computeLimit.cc
- test/hzz2l2v/samples.json
Hi all,
1- I have inserted a new alpha value using the new results.
2- Change a little thing in the function to compute NRBckg
3- Changed Tri-Boson tag into ZVV
Alessio
> New Little Changes

- bin/common/computeLimit.cc
New values of NRB in mumu channel.
Alessio
> New NRB values

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
Hi Loic,
Here you are the part of the code where the theoretical uncertainties are implemented.
Check it and let me know!
Alessio
> Implemented Theor Uncertainties

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
add the Jet energy uncertainties and the jet energy corrections on jets 
the uncertainties are updated to 2015 ones
> add the uncertainties on jet energy 

- src/EwkCorrections.cc
An update of the related plot is coming (very) soon. Then I will update the AN.
> Update of the way the uncertainties are computed.

- README.md
- scripts/runAnalysisOverSamples.py
New README.md and I remove a print for debugging that I previously forget
> New README.md

- TAGS.txt
Fix the compilation problem
Alessio
> New SVfit_standalone Tag

- scripts/runAnalysisOverSamples.py
I have removed the comment at line 118
Alessio
> remove the comment at line 118.. :-)

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- scripts/runAnalysisOverSamples.py
Dear all, 
Regarding my last email in the 2l2v mailing list, here is the fix for the das_client, using the cvmfs version of it.
Furthremore, I added a small bug fix for the rochcor.
Cheers,
Hugo
> Fixing das_client

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
This fixes problems when running on MC samples with my new additions. It basically fixes a lot of shadowing. A PR adding new json files for 80X will follow (probably on Thursday/Friday) (75% done at the moment)
> Fixing 2016 addition

- src/HxswgUtils.cc
Hi all,
I have fixed the problem related to BR we had during Moriond.
Alessio
> Br for GGH and VBF

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
I have removed the part of the file that has given the bug on the met distribution for VBF 1000 GeV
> Fix bug VBF 1000 GeV

- test/hzz2l2v/missing_samplesFor2016.json
- test/hzz2l2v/samples2016.json
New SM Signal Samples from 200GeV up to 2500GeV added in 80X
> New SM Samples up to 2500 GeV in 80X

- test/hzz2l2v/samples2016.json
Added Signal Samples for Radion and RsGraviton in 80X
> Added Radion and RsGraviton samples in 80X

- test/hzz2l2v/submit.sh
The Bug was this part:
params="@data_pileup=datapileup_2016 @jacknife=0 @saveSummaryTree=True @runSystematics=False @useMVA=True @jacks=0"
which is different for step 1.2 because we have to take into account also the photon weights.
Now it takes into account both the different pileup scenario and the photon weights.
> 22 july2016 in1 post ichep2016

- bin/chhiggs/runAnalysis.cc
- bin/common/computeLeptonEfficency.cc
- bin/common/runEfficencyMiniAODExample.cc
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/LeptonEfficiencySF.h
- interface/PatUtils.h
- src/PatUtils.cc
make the updates for electron/muon ID and SFs
> make the updates for electron/muon ID and SFs

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Photon Selection bug fixed
Alessio
> 23 august2016 cmssw 7 6 3

- scripts/LaunchOnCondor.py
I sometimes add things in this file and it's nearly impossible to do so.
Indeed, indentation is super important in python code and this code is a mess. Sometimes using Tab, sometimes using 4 spaces, sometimes 5... sometimes 3... Most of the time having different convention inside the same function... 
Therefore I made the effort to change it by hand (was so messy than not a single other method worked...) and here is the result.
So it adds nothing but allows more easy changes and readibility !
Changes in the file will come in an other PR.
> Clean LaunchOnCondor bad formatting

- src/GammaWeightsHandler.cc
Added the TGraph for the weights obtained using fitting functions
> Fitting Function to use for PhotonReweight

- scripts/LaunchOnCondor.py
- scripts/runAnalysisOverSamples.py
- test/hzz2l2v/submit.sh
This change nothing for people not working at IIHE.
However, for those at IIHE it will change the way jobs are sent. Without entering technicalities, this allows to run more than 2500 jobs in a row at IIHE. You should barely notice the change in the procedure.
For more details, ping me or see my slides at the 2l2nu meeting on the 8th of September.
> Big submission iihe

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/LeptonEfficiencySF.h
Hi Please find the full changes done!
I have changed our main analysis code as well. Also I ensure that Trigger efficiency fetched by code according to SCeta.
Please point me if I missed something. Though it is compiling perfectly fine.
I attached reference to the slides where I showed this study in this comment.
https://indico.cern.ch/event/535808/contributions/2278379/attachments/1324645/1987966/HZZ2l2v_August_18_2016.pdf
> diEle trig eff for ICHEP2016

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/LeptonEfficiencySF.h
Adding the muon trigger efficiency as discussed in today's meeting
Sorry I cannot resist to re-indent the function to make it more readable ;)
> add preliminary set of muon trigger efficiencies 

- test/hzz2l2v/submit.sh
Re-adding a line deleted by mistake on a previous old PR #212 .
> Re-adding a line deleted by mistake on a previous old PR212

- bin/hzz2l2v/extractPhotonWeights_UsingBins.cc
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- MC option passed in arguments in extractPhotonweights_UsingBins
- MET, MET axes limits reduced for aesthetics purposes
> passed MC option; fixed met,mt axes limits

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/LeptonEfficiencySF.h
- interface/PhotonEfficiencySF.h
- test/hzz2l2v/samples_ichep2016.json
- test/hzz2l2v/submit.sh
- lepton tracking eff and photon energy SFs
- removed spin-0 Radion model from samples_ichep2016.json
- fixed typo in photonZClosure
- added control plots of leading jet pt, eta, phi at pre-selection level
> lepton tracking eff and photon energy SFs

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- scripts/runAnalysisOverSamples.py
- test/hzz2l2v/submit.sh
- Gives the right path for rho_weight file.
- Add the default value when no file is specified.
> Improving rho weight

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
I have updated all the triggers. Please take a look!!
Also you can find all triggers in attached slides. It is in Zip. I tried to upload pdf but it was not uploading somehow.
[Triggers.pdf.zip](https://github.com/cms2l2v/2l2v_fwk/files/680459/Triggers.pdf.zip)
> Added all the required triggers for Moriond17

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
Hi All,
I have added tkHighPT ID for Muon.
Please take a look. 
Thanks,
Sumit
> added tkHighPT muon ID

- test/hzz2l2v/samples_full2016.json
Update WG sample for full2016 (from LO to NLO)
> Update WG sample for full2016

- scripts/runAnalysisOverSamples.py
This fixes PR #259 for lxplus.
> Hot fix for lxplus submission

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
Hi All,
I have added Bad and Duplicate Muon filter following Giovanni's recipe[1].
[1] https://github.com/gpetruc/cmssw/blob/badMuonFilters_80X/RecoMET/METFilters/plugins/BadGlobalMuonTagger.cc
Thanks to @georgia14  and @HuguesBrun !
> added Bad and Duplicate muon Filter

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- test/hzz2l2v/submit.sh
- added a clear control plot for all metFilters 
- latest bad + duplicate muon cleaning metFilters are not (yet) applied , only used to fill the metFilter histogram.
- updated a bit submit.sh : full2016 json by default . Hopefully fixed issue with missing histograms when merging
> small update for metFilters study

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
> Revert "small fix for triggerResults with newMC"

- test/hzz2l2v/samples_Moriond17.json
Merging this PR will automatically included the updates from Alessio in the dataset JSON file
> corrections of the dataset JSON file 

- test/hzz2l2v/samples_Moriond17.json
- test/hzz2l2v/samples_Moriond17_MELA_ContinuumOnly.json
- test/hzz2l2v/samples_Moriond17_MELA_Signal.json
2 bg samples are still missing:
TTTo2L2Nu_13TeV
ST_t-channel_antitop_4f_leptonDecays_13TeV
> Update of the samples JSON, including now the update of the signals

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Made quickly the PR but tests on signal are still running: I will post the signal shape here when I will have it
> revert back to ICHEP config

- src/HiggsUtils.cc
New weights for 100, 10 and 0 GeV for the width
> Pre approval moriond2017 cern

- test/hzz2l2v/samples_full2016.json
> Revert "Remove ggZZ Bckg from the json file"

- test/hzz2l2v/computeLimit/optimize.py
- test/hzz2l2v/samples_full2016.json
> Revert "Pre approval moriond2017 cern"

- test/hzz2l2v/samples_full2016.json
Addition of the datadriven mixing part: Top/W/WW; Genuine (ewk) MET inv; Genuine (ewk) MET; Instr. MET.
> Add the missing mixing parts to the json file

- test/hzz2l2v/samples_full2016_GGH.json
This commit updates the WJets merging in samples_full2016_GGH.json.
> Update samples_full2016_GGH.json for WJets merging

- test/hzz2l2v/computeLimit/finalLimitPlot_WideWidth.py
- test/hzz2l2v/computeLimit/optimize_WideWidth.py
Hi upload the two files I used to compute the limits.
there is only a thing to take care: the range to use to set the limit
For all the masses and both the width it is 0, 100 
like here:
--setPhysicsModelParameters CMS_zz4l_mu=0.0 -t -1 --setPhysicsModelParameterRanges CMS_zz4l_mu=0.0,100
BUT for 200 GeV and Γ=10 it has to be set at 1000
Here it the line to be changed:
--setPhysicsModelParameters CMS_zz4l_mu=0.0 -t -1 --setPhysicsModelParameterRanges CMS_zz4l_mu=0.0,1000
> Optimize files to run on WideWidth

- test/hzz2l2v/samples_full2016_GGH.json
- new DYJetsToLL M50toInf sample appeared with 122M events
> switched to the new DY sample amcatnlo

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
(It was actually ready, but not implemented)
> Actually apply electroweak corrections to WZ

- bin/common/computeLimit.cc
- python/HiggsWidth.py
- test/hzz2l2v/computeLimit/optimize_WideWidth.py
New implementation of the cross section inside the fitting model to avoid the range tuning
the procedure to obtain the limits is always the same.
python optimize_NewWidth.py -p 1/2/3/4/5
> Approval moriond2017 lxplus

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
This would allow to look at the effect of uncertainties with no MET cut, as needed for our MT and MET control plots
> Add a bin in the shapes with a MET cut of 0

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Hi All,
I have updated code for take uncertainty from electron scale correction in account. I'm really thankful of Li for helping me to setup this code. 
In case of any doubt. Please let me know.
Regards,
Sumit
> added systematic part for electron scale corrections

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Hi,
We are now back to old configuration for electron scale correction. I kept the systematic part in the code.
In the mean time I'm submitting jobs to figure out the what was going wrong with this new configuration.
> back to old configuration for ele scale correction

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/LeptonEfficiencySF.h
- interface/PhotonEfficiencySF.h
Hi All,
Now we have updated SF for full2016 data for Electron ID+ISO+Trig. Also for Muon ID's with SF for tkHighPT ID. Now the only SF are left are Muon Iso and Trigger.
> SF for electron ID+ISO+Trig and for Muon tkHighPT ID

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
There is also a small fix on the electron energy scale variation.
> bugfix for reading selJets in systematic variation

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- test/hzz2l2v/computeLimit/optimize.py
- test/hzz2l2v/computeLimit/optimize_WideWidth.py
Due to the addition of a new bin with no MET cut in the mt_shapes, the projection bin has to be changed to 17 instead of 16.
Furthermore I also use this PR to add the function introduced to be sure to update the 4-vector of the electron inside the if condition.
> Correction of the projection bin for mt shapes

- README.md
- bin/BuildFile.xml
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
Hi All,
please find the setup and instruction to run this setup for reminiAOD.
You need to add few packages from Egamma and clone the code from re-miniAOD-setup branch.
All the instructions are updated in README.md when you switch to re-miniAOD-setup branch.
Apart from checking out few Egamma packages everything is same.
Let me know in case of any doubt.
Regards,
Sumit
> Setup for re-MiniAOD

- scripts/LaunchOnCondor.py
This needs to be tested but could potentially fix AAA issue (https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookXrootdService#lxplusWarning)
> Trying to fix AAA issue at lxplus

- README.md
- bin/BuildFile.xml
- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
- interface/PatUtils.h
- src/PatUtils.cc
Hi ,
Here is the old setup.
I have updated REDAME.md as well to get this setup.
Regards,
Sumit
> Old Moriond17 miniAOD setup to run over re-Reco

- test/hzz2l2v/samples_full2016_GGH.json
Json file changed in such a way there is no splitting for the signal
Alessio
> Signal Without Splitting

- test/hzz2l2v/samples_full2016_MELA_Signal.json
Removed the splitting fleg in both VBF and GGH
Alessio
> No Splitting for Both GGH and VBF signa

- src/HiggsUtils.cc
New VBF Continuum Weights
Alessio
> New VBF Weights

- bin/hzz2l2v/runHZZ2l2vAnalysis.cc
Fix the 2d empty plot due to the NaN entries.
> VBF Bug fix

- test/hzz2l2v/macro_Intr_MET_Syst/MakeSyst_custom_forMTandMET.C
- test/hzz2l2v/macro_Intr_MET_Syst/customScriptsForSpecificAnalysis/produceAllMT_Control_Plots_SystBySyst.sh
- test/hzz2l2v/macro_Intr_MET_Syst/customScriptsForSpecificAnalysis/produceAllMTplotShapeOnly.sh
- test/hzz2l2v/macro_Intr_MET_Syst/customScriptsForSpecificAnalysis/produceAllSystShapeOnly.sh
- test/hzz2l2v/macro_Intr_MET_Syst/produceInstrMET_syst_rootFiles.sh
This is the commit to produce the needed files for Instr MET systematics.
The linked limit parts still need to be added (Alessio?).
To use this, you need:
1) a plotter.root in the test/hzz2l2v/ which contains all the 2D mt shapes for all process involved in InstrMET and the instrMET process itself.
2) then launch the script: test/hzz2l2v/macro_Intr_MET_Syst/produceInstrMET_syst_rootFiles.sh
This will create two root files in  data/InstrMET_systematics/ that will be used by the computeLimit.cc code.
The two files produced are:
- InstrMET_systematics_ALL_EXCEPT_GAMMASTATS.root : which contains systematics due to genuine MET substraction (XS, stats, corrections) and the method
- InstrMET_systematics_GAMMASTATS.root : which contains systematics due to the stats on gamma+jets
For developers, …
>  	Systematics root file production for InstrMET

- bin/common/computeLimit.cc
- test/hzz2l2v/computeLimit/finalLimitPlot_WideWidth.C
- test/hzz2l2v/submit.sh
Two changes:
1- submit.sh --> to generate the plotter.root with only 2D histo
2- computeLimit.cc --> new binning for Mt shape considering the jet bins category
Cheers,
Alessio
> Eps branch lxplus

- test/hzz2l2v/computeLimit/optimize_WideWidth.py
New commands to obtain the plots of the pull
Alessio
> New combine command

- bin/common/computeLimit.cc
> jetBin declaration

- BuildFile.xml
- README.md
- bin/common/computeLimit.cc
- interface/MacroUtils.h
- src/MacroUtils.cc
- test/hzz2l2v/macro_Intr_MET_Syst/MakeSyst_custom_forMTandMET.C
- test/hzz2l2v/macro_Intr_MET_Syst/produceInstrMET_syst_rootFiles.sh
1) Changing readme files to make it more coherent and adding MELA in the code by default.
2) Adding instrMET systematics to computeLimits and related files
3) Updating instrMET systematics production to be able to change the binning between categories.
NB: There are, especially in the computeLimit.cc a lot of differences in indentation. Please look at this link: https://github.com/cms2l2v/2l2v_fwk/compare/master...hdelanno:InstrMETSystforComputingLimits?w=1 to have a clearer view of what was changed.
> Instr met syst for computing limits

- bin/common/computeLimit.cc
New VBF binning following Higgs suggestion and request.
Cheers,
Alessio
> New VBF Binning

- test/hzz2l2v/computeLimit/finalLimitPlot_WideWidth.C
- test/hzz2l2v/computeLimit/plotLimit.C
transmited to me this afternoon by Alessio (cc @amagitte )
> update to plot the limits 

- bin/common/computeLimit.cc
- test/hzz2l2v/macro_Intr_MET_Syst/MakeSyst_custom_forMTandMET.C
- update the VBF binning from @ly615 
- update the MET inst from @hdelanno
> update VBF binning + update MET inst. 

- bin/common/computeLimit.cc
Contains the last MET uncertainty file form @hdelanno + the other changes described in [last Friday talk](https://indico.cern.ch/event/650502/contributions/2655064/attachments/1489872/2315471/impacts2l2nu_Hugues.pdf)
> Update the Inst. MET. uncertainties 
